services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/viajes_recomendacion                   # Monta el código local para hot-reloading
      #- venv:/app/venv           # Persiste dependencias (opcional)
    tty: true 
    command: tail -f /dev/null  # Mantiene el contenedor en ejecución

  #data_generator:     # Servicio para generar datos de prueba. Desactivado por defecto.
    #build: .
    #environment:
      #- MONGO_URI=mongodb+srv://mcabreraezequiel:ZUH7u03ZsPXN7jYk@ingdatos.hzoisln.mongodb.net/?retryWrites=true&w=majority&appName=IngDatos
      #- DB_NAME=viajes_recomendacion
    #command: python src/data_generator.py  # Genera datos al iniciar
    #volumes:
      #- .:/app                   # Sincroniza código (si el script se modifica)
#volumes:
  #venv:                          # Volumen para persistir el entorno virtual

