services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5051:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de la máquina host
    volumes:
      - .:/viajes_recomendacion                   # Monta el código local para hot-reloading
      #- venv:/app/venv           # Persiste dependencias (opcional)
    tty: true 
    command: tail -f /dev/null  # Mantiene el contenedor en ejecución



